### ISSUE TITLE
Endpoint doesn't found

### ISSUE THREAD

**Issue by mahmudunnabikajal** [xaadu/ostad_docker_assignment_1_batch_1#1]
@xaadu 

Filename: README.md

Resolve: Change the endpoint name `http://localhost:<given_port>/healthcheck` to `http://localhost:<given_port>/health` in instruction file. The given endpoint doesn't exist in `main.go`

**Comment by xaadu** [comment]
Thanks a lot, brother. It was mixed up with another project. Check the updated readme, please.
